#!/usr/bin/env perl
# vim:ts=4:sw=4:expandtab
# © 2011 Michael Stapelberg (see also: LICENSE)

use strict;
use warnings;
use feature qw(say);
use Getopt::Long;
use FindBin;
use lib "$FindBin::Bin/../lib";
use RaumZeitLabor::BenutzerDB::Pinvalidator;

GetOptions(
    'version' => sub {
        say "$0 v$RaumZeitLabor::BenutzerDB::Pinvalidator::VERSION";
        exit 0;
    },
    'help' => sub {
        say "$0: no options, started via initscript.";
        exit 0;
    }
);

RaumZeitLabor::BenutzerDB::Pinvalidator->run();

